# Generated by Django 4.2.16 on 2026-09-14 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='菜单名称')),
                ('path', models.CharField(blank=True, default='', max_length=200, verbose_name='路由路径')),
                ('component', models.CharField(blank=True, default='', max_length=200, verbose_name='组件路径')),
                ('icon', models.CharField(blank=True, default='', max_length=50, verbose_name='图标')),
                ('menu_type', models.CharField(choices=[('catalog', '目录'), ('menu', '菜单'), ('button', '按钮')], default='menu', max_length=20, verbose_name='类型')),
                ('permission', models.CharField(blank=True, default='', max_length=100, verbose_name='权限标识')),
                ('sort', models.IntegerField(default=0, verbose_name='排序')),
                ('visible', models.BooleanField(default=True, verbose_name='是否显示')),
                ('status', models.BooleanField(default=True, verbose_name='启用状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='system.menu', verbose_name='上级菜单')),
            ],
            options={
                'verbose_name': '菜单',
                'verbose_name_plural': '菜单',
                'db_table': 'sys_menu',
                'ordering': ['sort', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='角色名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='角色编码')),
                ('description', models.CharField(blank=True, default='', max_length=200, verbose_name='描述')),
                ('status', models.BooleanField(default=True, verbose_name='启用状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('menus', models.ManyToManyField(blank=True, related_name='roles', to='system.menu', verbose_name='菜单权限')),
            ],
            options={
                'verbose_name': '角色',
                'verbose_name_plural': '角色',
                'db_table': 'sys_role',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='部门名称')),
                ('sort', models.IntegerField(default=0, verbose_name='排序')),
                ('leader', models.CharField(blank=True, default='', max_length=50, verbose_name='负责人')),
                ('phone', models.CharField(blank=True, default='', max_length=20, verbose_name='联系电话')),
                ('status', models.BooleanField(default=True, verbose_name='启用状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='system.department', verbose_name='上级部门')),
            ],
            options={
                'verbose_name': '部门',
                'verbose_name_plural': '部门',
                'db_table': 'sys_department',
                'ordering': ['sort', 'id'],
            },
        ),
    ]
